// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxG5bgrqENksHRfXHWAqOKByvLG_MP05w',
    appId: '1:1087600511846:web:d20e7b1905d129d11e56a7',
    messagingSenderId: '1087600511846',
    projectId: 'banking-app-c5ae9',
    authDomain: 'banking-app-c5ae9.firebaseapp.com',
    storageBucket: 'banking-app-c5ae9.firebasestorage.app',
    measurementId: 'G-JCRE8VLXP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfjMRwMwmGOoNg8VAVWdm2HggXRSTJ3eE',
    appId: '1:1087600511846:android:6fdca81aa7925bf91e56a7',
    messagingSenderId: '1087600511846',
    projectId: 'banking-app-c5ae9',
    storageBucket: 'banking-app-c5ae9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMRSc3_8odAs8mAREeNNGBWboFshPmzE',
    appId: '1:1087600511846:ios:b893691cf066f0941e56a7',
    messagingSenderId: '1087600511846',
    projectId: 'banking-app-c5ae9',
    storageBucket: 'banking-app-c5ae9.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWMRSc3_8odAs8mAREeNNGBWboFshPmzE',
    appId: '1:1087600511846:ios:b893691cf066f0941e56a7',
    messagingSenderId: '1087600511846',
    projectId: 'banking-app-c5ae9',
    storageBucket: 'banking-app-c5ae9.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxG5bgrqENksHRfXHWAqOKByvLG_MP05w',
    appId: '1:1087600511846:web:f154c50f8d1843e11e56a7',
    messagingSenderId: '1087600511846',
    projectId: 'banking-app-c5ae9',
    authDomain: 'banking-app-c5ae9.firebaseapp.com',
    storageBucket: 'banking-app-c5ae9.firebasestorage.app',
    measurementId: 'G-1K64PBTGFV',
  );
}
