// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy2oZNpYbG3_XmsUMewpzEvvdSp7OMlPQ',
    appId: '1:269700130298:web:a8e052293512980b473043',
    messagingSenderId: '269700130298',
    projectId: 'gen-lang-client-0735548844',
    authDomain: 'gen-lang-client-0735548844.firebaseapp.com',
    storageBucket: 'gen-lang-client-0735548844.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJKvvvNo6a8dnqMZW__JITCDzff0fZrI',
    appId: '1:269700130298:android:d5eb0e6264257895473043',
    messagingSenderId: '269700130298',
    projectId: 'gen-lang-client-0735548844',
    storageBucket: 'gen-lang-client-0735548844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8KEP_s8LUTtNprBKYFjjTrqdTHnDyqk',
    appId: '1:269700130298:ios:3c9eff74a1290d27473043',
    messagingSenderId: '269700130298',
    projectId: 'gen-lang-client-0735548844',
    storageBucket: 'gen-lang-client-0735548844.firebasestorage.app',
    iosClientId: '269700130298-3drqi6ae0il39gp12fft8k54jtk5qvjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO8KEP_s8LUTtNprBKYFjjTrqdTHnDyqk',
    appId: '1:269700130298:ios:3c9eff74a1290d27473043',
    messagingSenderId: '269700130298',
    projectId: 'gen-lang-client-0735548844',
    storageBucket: 'gen-lang-client-0735548844.firebasestorage.app',
    iosClientId: '269700130298-3drqi6ae0il39gp12fft8k54jtk5qvjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy2oZNpYbG3_XmsUMewpzEvvdSp7OMlPQ',
    appId: '1:269700130298:web:37673eb9fc9307f4473043',
    messagingSenderId: '269700130298',
    projectId: 'gen-lang-client-0735548844',
    authDomain: 'gen-lang-client-0735548844.firebaseapp.com',
    storageBucket: 'gen-lang-client-0735548844.firebasestorage.app',
  );
}
